import Head from "next/head";
import Featured from "../components/Featured";
import Info from "../components/Info";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Helping Hands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <Info />
    </div>
  );
}
